---
title: "First Pass at Fitting Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gbm)
```

```{r}
final_pitch_data <- read_csv("data/final_pitch_data.csv")

#Removing "ball" outcomes
balls<- final_pitch_data %>% filter(type == "B")

final_pitch_data_nob <- anti_join(final_pitch_data,balls)

final_pitch_data_nob<-final_pitch_data_nob %>% drop_na()

#Dropping 0 values (should be NA but statcast codes them as 0, a release speed or an effective speed of 0 is impossible thus is dropped)
final_pitch_data_nob<- final_pitch_data_nob[final_pitch_data_nob$release_speed !=0,]
final_pitch_data_nob<- final_pitch_data_nob[final_pitch_data_nob$release_speed !=0,]
```

```{r}
final_pitch_model<-final_pitch_data_nob %>% dplyr::select (-pitch_type,-pitch_name,-player_name,-batter,-xwoba,-hit_location)

#This mutation is necessary for the bernoulli distribution in the boosted model below, which requires 0's and 1's
final_pitch_model<- final_pitch_model%>% mutate(type2=ifelse(type == "S",0,1))

train<-final_pitch_model %>% dplyr::select(-type) %>% sample_frac(.75)
test<-anti_join(final_pitch_model,train)

Auto_lda<-lda(type~.,data=train)
lda_pred<-predict(Auto_lda, test)

class<-data.frame(lda_pred$posterior)
confusionMatrix(data=factor(lda_pred$class),reference=factor(test$type))


roc_curve<-roc(response=test$type,predictor=class$X)
ggroc(roc_curve,legacy.axes="True")
auc(roc_curve)

```

```{r}
boosted_tree<-gbm(type2 ~., train,
distribution = "bernoulli",
n.trees=50,
interaction.depth = 1,
shrinkage = 0.1)

set.seed(0)

boost_pred<-ifelse (predict(boosted_tree,test,type="response")>=0.5,1,0)


confusionMatrix(data=factor(boost_pred),reference=factor(test$type2))

```


